class ProtocolException(Exception): ...


class CRLFNotFound(ProtocolException): ...


class MalformedAuthority(ProtocolException): ...


class UnsupportedScheme(ProtocolException): ...


class MalformedURI(ProtocolException): ...


class UnexpectedEOM(ProtocolException): ...


class InvalidSize(ProtocolException): ...
