from typing import Protocol


class ReceiveBufferContract(Protocol):
    @property
    def buffer(self) -> bytearray: ...

    def is_empty(self) -> bool: ...
    def put_data(self, data: bytes) -> None: ...

    def read_until_crlf(self) -> bytes: ...
    def read_at_most(self, byte_count: int) -> bytes | None: ...
    def read_eom(self) -> None: ...

    def consume(self) -> bytes: ...
