from typing import Protocol


class ReceiveBufferContract(Protocol):
    def put_data(self, data: bytes | bytearray) -> None: ...
    
    def read_until_crlf(self) -> bytes | None: ...
    def read_at_most(self, byte_count: int) -> bytes | None: ...
